# Practical session 3 - Practice with numpy

Course: [SDIA-Python](https://github.com/guilgautier/sdia-python)

Date: 10/06/2021

Instructor: [Guillaume Gautier](https://guilgautier.github.io/)

Students (pair):
- [Student 1]([link](https://github.com/username1))
- [Student 2]([link](https://github.com/username2))

In [1]:
%load_ext autoreload
%autoreload 2

import numpy as np
from lab2.utils import get_random_number_generator

In [2]:
my_array = np.array([0])
print(type(my_array))
dir(np.ndarray)

<class 'numpy.ndarray'>


['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

Propose at leat 2 ways to create an integer vector of size 100 made of 1s

In [6]:
V1 = np.ones(100)
V2 = np.zeros(100)+1
V3 = np.array([1]*100)

print(np.array_equal(V1,V2))
print(np.array_equal(V1,V3))

True
True


Create a vector with values ranging from 10 to 49

In [8]:
V1 = np.arange(10,50,1)
print(V1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Propose a way to construct the vector $(0.0, 0.2, 0.4, 0.6, 0.8)$

In [9]:
V1 = np.arange(0,1,0.2)
print(V1)

[0.  0.2 0.4 0.6 0.8]


Convert a float array into an integer array in place

In [16]:
V1 = np.arange(0,30,np.pi)
print(V1)
V2 = V1.astype(int)
print(V2)

[ 0.          3.14159265  6.28318531  9.42477796 12.56637061 15.70796327
 18.84955592 21.99114858 25.13274123 28.27433388]
[ 0  3  6  9 12 15 18 21 25 28]


Given a boolean array

- return the indices where 
- negate the array inplace? 

In [38]:
V = np.random.choice([False, True], size=(10))
print("V      : ",V)
Ind = np.where(V==True)
print("Indices of True values in V : ",Ind)

print("not(V) : ",np.logical_not(V))
print("not(V) : ",np.invert(V))

V      :  [False False False  True False  True  True  True  True  True]
Indices of True values in V :  (array([3, 5, 6, 7, 8, 9], dtype=int64),)
not(V) :  [ True  True  True False  True False False False False False]
not(V) :  [ True  True  True False  True False False False False False]


Given 2 vectors $u, v$, propose at least

- 2 ways to compute the inner product $v^{\top} u$ (here they must have the same size)
- 2 ways to compute the outer product matrix $u v^{\top}$
- 2 ways to compute the outer sum matrix "$M = u + v^{\top}$", where $M_{ij} = u_i + v_j$

In [53]:
U = np.random.randint(0,10,5)
V = np.random.randint(0,10,5)

inner_prod1 = (U).dot(V)
inner_prod2 = np.sum(U*V)
print("inner product : ", inner_prod1, inner_prod2)

outer_prod1 = U[:, None].dot(V[None, :])
outer_prod2 = np.outer(U,V)
print("outer product : \n", outer_prod1, "\n", outer_prod2)

sum1 = U + np.flip(V)
sum2 = U + V[::-1]
print("sum : ", sum1, sum2)


inner product :  23 23
outer product : 
 [[ 0  5  5  5 25]
 [ 0  2  2  2 10]
 [ 0  2  2  2 10]
 [ 0  4  4  4 20]
 [ 0  3  3  3 15]] 
 [[ 0  5  5  5 25]
 [ 0  2  2  2 10]
 [ 0  2  2  2 10]
 [ 0  4  4  4 20]
 [ 0  3  3  3 15]]
sum :  [10  3  3  5  3] [10  3  3  5  3]


Given the following matrix

$$
M = 
\begin{pmatrix}
    0 & 1 & 2 \\
    3 & 4 & 5 \\
    6 & 7 & 8 \\
\end{pmatrix}
$$

- Create $M$ using as a list of lists and access the element in the middle
- Propose at least 2 ways to create $M$ using numpy and access the element in the middle
- Swap its first and second row
- Propose at least 3 ways to extract the submatrix $\begin{pmatrix}4 & 5 \\7 & 8 \\\end{pmatrix}$
- Propose at least 2 ways to extract the diagonal of $M$
- Propose at least 2 ways to compute $M^3$
- Compute $v^{\top} M$, resp. $M N$ for a vector, resp. a matrix of your choice. 
- Propose 2 ways to "vectorize" the matrix, i.e., transform it into
  - $(0, 1, 2, 3, 4, 5, 6, 7, 8)$
  - $(0, 3, 6, 1, 4, 7, 2, 5, 8)$
- Consider $v = (1, 2 , 3)$, compute the
  - row-wise multiplication of $M$ by $v$ ($M_{i\cdot}$ is multiplied by $v_i$)
  - column-wise multiplication of $M$ by $v$ ($M_{\cdot j}$ is multiplied by $v_i$)

In [75]:
M = [[3*i+j for j in range(3)] for i in range(3)]
print(M)
print("middle element : ", M[1][1], "\n")

M1 = np.reshape(np.arange(0,9,1),(3,3))
M2 = np.fromfunction(lambda i, j: 3*i+j, (3, 3),dtype=int)
print("initialize matrix :\n", M1, "\n", M2, "\n")

print("acess element :\n", M1[1,1],M[1][1], "\n")

subM1 = M1[1:,1:]
subM2 = M1[[1,2]][:,[1,2]]
subM3 = M1
print("submatrix :\n",subM1,"\n", subM2, "\n", subM3, "\n")

diag1 = np.diag(M1)
diag2 = np.diagonal(M1)
print("diagonal :\n",diag1,"\n", diag2, "\n")

M3pow1 = np.linalg.matrix_power(M1, 3)
M3pow2 = M1.dot(M1.dot(M1))
print("M^3 :\n", M3pow1,"\n", M3pow2, "\n")


[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
middle element :  4 

initialize matrix :
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

acess element :
 4 4 

submatrix :
 [[4 5]
 [7 8]] 
 [[4 5]
 [7 8]] 
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

diagonal :
 [0 4 8] 
 [0 4 8] 

M^3 :
 [[ 180  234  288]
 [ 558  720  882]
 [ 936 1206 1476]] 
 [[ 180  234  288]
 [ 558  720  882]
 [ 936 1206 1476]] 



Write a function `is_symmetric` that checks whether a given n x n matrix is symmetric, and provide an example

## Random

REQUIREMENT: USE THE FUNCTION `get_random_number_generator` as previously used in Lab 2.

Consider the Bernoulli(0.4) distribution

- Propose at least 2 ways to generate n=1000 samples from it
- Compute the empirical mean and variance

Consider a random matrix of size $50 \times 100$, filled with i.i.d. standard Gaussian variables, compute

- the absolute value of each entry
- the sum of each row
- the sum of each colomn 
- the (euclidean) norm of each row
- the (euclidean) norm of each column